version: '3.9'

services:
  nginx:
    image: nginx:1.23.1-alpine
  depends_on:
    - django
  ports:
    - "80:80"
  volumes:
    - static_/var/www/html/static
    - ./nginx-conf.d:/etc/nginx/conf.d

  django:
    build: ./app
    command: python start
    volumes:
      - ./app:/app
      - static_data:/
    expose:
      - 8000
    environment:
      - DATABASE_URL=url
      - DEBUG=1